package com.payment.gateway.common.enums;

public enum ErrorCode {
    MERCHANT_ALREADY_EXISTS,
    RESOURCE_NOT_FOUND,
    VALIDATION_FAILED,
    INTERNAL_SERVER_ERROR,
    MERCHANT_NOT_FOUND,
    KEY_NOT_FOUND,
    DUPLICATE_RESOURCE,
    ORDER_NOT_FOUND,
    FORBIDDEN
}
