package com.payment.gateway.common.enums;

public enum PaymentEvent {
    PAYMENT_CREATED,
    AUTHORIZATION_REQUESTED,
    AUTHORIZATION_SUCCEEDED,
    AUTHORIZATION_FAILED,
    CAPTURE_REQUESTED,
    CAPTURE_SUCCEEDED,
    CAPTURE_FAILED,
    REFUND_REQUESTED,
    REFUND_SUCCEEDED,
    REFUND_FAILED,
    VOID_REQUESTED,
    VOID_SUCCEEDED,
    VOID_FAILED,
    CHARGEBACK_RECEIVED,
    CHARGEBACK_REVERSED,
    SETTLEMENT_COMPLETED,
    SETTLEMENT_FAILED,
    PAYMENT_EXPIRED,
    PAYMENT_CANCELLED,
    FRAUD_DETECTED,
    DISPUTE_OPENED,
    DISPUTE_RESOLVED
}

